Repository wecode-bootcamp-korea/42-2nd-smallbox-frontend, pull requests merged in 2023-03, with the labels that each got.

#4 [42기 이해인]Feature/login
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/pages/Booking/Booking.js
  src/pages/Login/KakaoAPI.js
  src/pages/Login/Login.js
  src/pages/Login/LoginContainer.js
  src/pages/Login/LoginLoading.js
  src/pages/Login/smallbox_logo.png
  src/pages/Login/withkakao.png
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#5 [42기 김수현] 메인페이지 1차 완료
  package-lock.json
  package.json
  public/data/SwiperMoviesData.json
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
  src/pages/Main/Swiper/Swiper.js
  src/pages/Main/Swiper/SwiperCard.js
  src/pages/Main/VideoSwiper/VideoSwiper.css
  src/pages/Main/VideoSwiper/VideoSwiper.js
  src/pages/Main/VideoSwiper/Videos.js
Labels: 완료

#6 [42기 이해인]ADD: 빠른예매-영화고르기(정렬X)
  public/data/movieSelect.json
  src/Router.js
  src/pages/Booking/BigIconChange.js
  src/pages/Booking/Booking.js
  src/pages/Booking/SelectMovie.js
  src/pages/Booking/SelectMovieHeader.js
  src/pages/Booking/SelectMovieMid.js
  src/pages/Booking/SelectMovieTop.js
  src/pages/Booking/listIcon.png
  src/pages/Booking/resetIcon.png
  src/pages/Booking/square.png
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 완료

#1 [42기 방서빈]ADD: footer 레이아웃 & 기능 구현 완료 / mock 데이터 적용 완료
  public/img/screen.png
  src/components/Footer/ SubsidiaryData.js
  src/components/Footer/Footer.js
  src/components/Footer/FooterData.js
  src/components/Footer/FooterInfo.js
  src/pages/Booking/Booking.js
  src/pages/Booking/DateBooking.js
Labels: Rebase 요청

#3 [42기 김수현] 예매창_시간, 결과 부분 component :: 리뷰 반영 완
  public/data/bookingTimeData.json
  public/data/movieData.json
  src/Router.js
  src/pages/Booking/Booking.js
  src/pages/Booking/BookingResult.js
  src/pages/Booking/BookingTime.js
  src/pages/Booking/Seats.js
  src/pages/Booking/Seats/Seats.js
  src/pages/Booking/images/icon_day.png
  src/pages/Booking/images/icon_night.png
Labels: 멘토 리뷰 요청

#11 [42기 이해인]ADD:상세페이지 구현 및 리뷰
  package-lock.json
  package.json
  public/data/dataGraph.json
  public/data/detailMovie.json
  public/data/selectMovie.json
  src/components/Nav/Nav.js
  src/pages/Login/LoginContainer.js
  src/pages/Main/Main.js
  src/pages/MovieDetail/CharmingGraph.js
  src/pages/MovieDetail/CheckBoxContext.js
  src/pages/MovieDetail/Checkbox.js
  src/pages/MovieDetail/CheckboxGroup.js
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieDetailVideoImage/DetailImg.js
  src/pages/MovieDetail/MovieDetailVideoImage/DetailVideo.js
  src/pages/MovieDetail/MovieReview.js
  src/pages/MovieDetail/ReviewLists.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#12 [42기 이해인]MODIFY: fetch주소변경
  src/pages/Login/KakaoAPI.js
Labels: 멘토 리뷰 요청

#10 [42기 김수현] 카카오페이 결제 구현 완료
  package-lock.json
  package.json
  src/Router.js
  src/pages/Booking/BookingResult.js
  src/pages/Booking/Payment/Payment.js
  src/pages/Booking/Payment/PaymentApproval.js
  src/pages/Booking/Payment/PaymentCancel.js
  src/pages/Booking/Payment/PaymentFail.js
  src/pages/Booking/Payment/PaymentResult.js
  src/pages/Booking/Payment/img/check-mark.png
  src/pages/Booking/Payment/img/smallbox_logo.png
  src/pages/Booking/SelectMovieHeader.js
  src/pages/Login/KakaoAPI.js
Labels: Conflict 해결 요청, Rebase 요청

#9 [42기 김수현] 좌석 선택창 레이아웃, 로직 구현
  package-lock.json
  public/data/SeatsData.json
  src/pages/Booking/Seats/PeopleCount.js
  src/pages/Booking/Seats/Seats.js
  src/pages/Booking/Seats/SeatsButton.js
  src/pages/Booking/Seats/images/icon_reset.png
Labels: 완료

#13 [42기 이해인]ADD:극장페이지/카카오맵구현
  package-lock.json
  package.json
  public/index.html
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Booking/Payment/Payment.js
  src/pages/Login/KakaoAPI.js
  src/pages/Main/VideoSwiper/Videos.js
  src/pages/Theater/Theater.js
  src/pages/Theater/TheaterLocation.js
  src/pages/Theater/smallbox_logo.png
Labels: 완료

#14 [42기 이해인]MODIFY : 메인수정
  public/data/SwiperMoviesData.json
  src/Router.js
  src/components/Footer/ SubsidiaryData.js
  src/components/Footer/Footer.js
  src/components/Footer/smallbox_logo.png
  src/components/Nav/Nav.js
  src/pages/Booking/Payment/PaymentApproval.js
  src/pages/Main/Main.js
  src/pages/Main/MainTop4.js
  src/pages/Main/Swiper/Swiper.js
  src/pages/Main/Swiper/SwiperCard.js
  src/pages/Main/VideoSwiper/VideoSwiper.js
  src/pages/Main/VideoSwiper/Videos.js
  src/pages/Main/laurel.png
  src/pages/MovieDetail/MovieDetail.js
  src/pages/MovieDetail/MovieDetailVideoImage/DetailImg.js
  src/styles/utils.js
Labels: 멘토 리뷰 요청

#17 [42기 김수현] 카카오페이 결제 플로우 구현 완
  package-lock.json
  package.json
  public/data/bookingTimeData.json
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Booking/BigIconChange.js
  src/pages/Booking/Booking.js
  src/pages/Booking/BookingResult.js
  src/pages/Booking/BookingTime.js
  src/pages/Booking/BookingTimeButton.js
  src/pages/Booking/DateBooking.js
  src/pages/Booking/DateComponent.js
  src/pages/Booking/DatePicker.js
  src/pages/Booking/DatePicker.module.css
  src/pages/Booking/Payment/Payment.js
  src/pages/Booking/Payment/PaymentApproval.js
  src/pages/Booking/Payment/PaymentResult.js
  src/pages/Booking/Seats.js
  src/pages/Booking/Seats/Seats.js
  src/pages/Booking/Seats/SeatsButton.js
  src/pages/Booking/SelectMovie.js
  src/pages/Booking/SelectMovieHeader.js
  src/pages/Booking/SelectMovieMid.js
  src/pages/Booking/SelectMovieTop.js
  src/pages/Login/KakaoAPI.js
  src/pages/Main/Swiper/Swiper.js
  src/pages/MovieDetail/MovieDetail.js
Labels: 완료
